// <auto-generated />
using System;
using DiversityPub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiversityPub.Migrations
{
    [DbContext(typeof(DiversityPubDbContext))]
    [Migration("20250724215837_Km01")]
    partial class Km01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActivationAgentTerrain", b =>
                {
                    b.Property<Guid>("ActivationsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentsTerrainId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActivationsId", "AgentsTerrainId");

                    b.HasIndex("AgentsTerrainId");

                    b.ToTable("ActivationAgentTerrain");
                });

            modelBuilder.Entity("DiversityPub.Models.Activation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampagneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateActivation")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time");

                    b.Property<Guid>("LieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampagneId");

                    b.HasIndex("LieuId");

                    b.ToTable("Activations");
                });

            modelBuilder.Entity("DiversityPub.Models.AgentTerrain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("AgentsTerrain");
                });

            modelBuilder.Entity("DiversityPub.Models.Campagne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Campagnes");
                });

            modelBuilder.Entity("DiversityPub.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailContactPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomContactPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomDirigeant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaisonSociale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistreCommerce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneContactPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DiversityPub.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentTerrainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgentTerrainId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("DiversityPub.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampagneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateFeedback")
                        .HasColumnType("datetime2");

                    b.Property<int>("Note")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampagneId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("DiversityPub.Models.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentTerrainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDeclaration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgentTerrainId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("DiversityPub.Models.Lieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lieux");
                });

            modelBuilder.Entity("DiversityPub.Models.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentTerrainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgentTerrainId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("DiversityPub.Models.PositionGPS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentTerrainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Horodatage")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AgentTerrainId");

                    b.ToTable("PositionsGPS");
                });

            modelBuilder.Entity("DiversityPub.Models.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "admin@diversitypub.ci",
                            MotDePasse = "$2a$11$sFOF2Rh9vaUbmtJaw07e2etMUOxAApCLxD54jpf5BhO0J0zRr7Spm",
                            Nom = "Super",
                            Prenom = "Admin",
                            Role = 1
                        });
                });

            modelBuilder.Entity("ActivationAgentTerrain", b =>
                {
                    b.HasOne("DiversityPub.Models.Activation", null)
                        .WithMany()
                        .HasForeignKey("ActivationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiversityPub.Models.AgentTerrain", null)
                        .WithMany()
                        .HasForeignKey("AgentsTerrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiversityPub.Models.Activation", b =>
                {
                    b.HasOne("DiversityPub.Models.Campagne", "Campagne")
                        .WithMany("Activations")
                        .HasForeignKey("CampagneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiversityPub.Models.Lieu", "Lieu")
                        .WithMany("Activations")
                        .HasForeignKey("LieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campagne");

                    b.Navigation("Lieu");
                });

            modelBuilder.Entity("DiversityPub.Models.AgentTerrain", b =>
                {
                    b.HasOne("DiversityPub.Models.Utilisateur", "Utilisateur")
                        .WithOne("AgentTerrain")
                        .HasForeignKey("DiversityPub.Models.AgentTerrain", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("DiversityPub.Models.Campagne", b =>
                {
                    b.HasOne("DiversityPub.Models.Client", "Client")
                        .WithMany("Campagnes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DiversityPub.Models.Client", b =>
                {
                    b.HasOne("DiversityPub.Models.Utilisateur", "Utilisateur")
                        .WithOne("Client")
                        .HasForeignKey("DiversityPub.Models.Client", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("DiversityPub.Models.Document", b =>
                {
                    b.HasOne("DiversityPub.Models.AgentTerrain", "AgentTerrain")
                        .WithMany("Documents")
                        .HasForeignKey("AgentTerrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentTerrain");
                });

            modelBuilder.Entity("DiversityPub.Models.Feedback", b =>
                {
                    b.HasOne("DiversityPub.Models.Campagne", "Campagne")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CampagneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campagne");
                });

            modelBuilder.Entity("DiversityPub.Models.Incident", b =>
                {
                    b.HasOne("DiversityPub.Models.AgentTerrain", "AgentTerrain")
                        .WithMany("Incidents")
                        .HasForeignKey("AgentTerrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentTerrain");
                });

            modelBuilder.Entity("DiversityPub.Models.Media", b =>
                {
                    b.HasOne("DiversityPub.Models.AgentTerrain", "AgentTerrain")
                        .WithMany("Medias")
                        .HasForeignKey("AgentTerrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentTerrain");
                });

            modelBuilder.Entity("DiversityPub.Models.PositionGPS", b =>
                {
                    b.HasOne("DiversityPub.Models.AgentTerrain", "AgentTerrain")
                        .WithMany("PositionsGPS")
                        .HasForeignKey("AgentTerrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentTerrain");
                });

            modelBuilder.Entity("DiversityPub.Models.AgentTerrain", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Incidents");

                    b.Navigation("Medias");

                    b.Navigation("PositionsGPS");
                });

            modelBuilder.Entity("DiversityPub.Models.Campagne", b =>
                {
                    b.Navigation("Activations");

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("DiversityPub.Models.Client", b =>
                {
                    b.Navigation("Campagnes");
                });

            modelBuilder.Entity("DiversityPub.Models.Lieu", b =>
                {
                    b.Navigation("Activations");
                });

            modelBuilder.Entity("DiversityPub.Models.Utilisateur", b =>
                {
                    b.Navigation("AgentTerrain");

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
